{
 "title": "Notification Service Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Notifications by Type",
   "type": "piechart",
   "description": "Распределение уведомлений по типам за 24 часа",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(notifications_sent_total[24h])) by (event_type)",
     "legendFormat": "{{event_type}}"
    }
   ]
  },
  {
   "title": "Total Notifications (last 24h)",
   "type": "stat",
   "description": "Всего отправлено уведомлений за последние 24 часа",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(increase(notifications_sent_total[24h]))",
     "legendFormat": "Total notifications"
    }
   ]
  },
  {
   "title": "Notifications Sent Rate (per minute)",
   "type": "timeseries",
   "description": "Скорость отправки уведомлений по типам",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "sum(rate(notifications_sent_total[5m])*60) by (event_type)",
     "legendFormat": "{{event_type}}"
    }
   ]
  }
 ]
}