{
 "title": "Product Service Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "JVM Heap Memory Usage",
   "type": "timeseries",
   "description": "Использование heap-памяти JVM",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{area=\"heap\", application=\"product-service\"})",
     "legendFormat": "Used memory"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{area=\"heap\", application=\"product-service\"})",
     "legendFormat": "Max memory"
    }
   ]
  },
  {
   "title": "Products Created (last 5 min)",
   "type": "timeseries",
   "description": "Количество продуктов, созданных за последние 5 минут",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(products_created_total[5m])",
     "legendFormat": "Products Created"
    }
   ]
  },
  {
   "title": "Total Requests (last hour)",
   "type": "gauge",
   "description": "Сколько всего запросов каждого типа было за последний час",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{application=\"product-service\"}[1h])) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "API Request Duration (average)",
   "type": "stat",
   "description": "Среднее время выполнения запросов за последние 5 минут",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{application=\"product-service\"}[5m])) by (method) / sum(rate(http_server_requests_seconds_count{application=\"product-service\"}[5m])) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  }
 ]
}