spring:
  application:
    name: notification-service
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  metrics:
    tags:
      application: ${spring.application.name}
    export:
      prometheus:
        enabled: true
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true